<template>
	<div class="aioseo-tab-content aioseo-post-general">
		<core-card
			v-if="allowed('aioseo_page_general_settings')"
			slug="postSettingsSearchAppearance"
			card-id="postSettingsSearchAppearance"
			:header-text="strings.searchAppearance"
			:hide-header="'modal' === props.parentComponentContext"
			:toggles="'modal' !== props.parentComponentContext"
			:no-slide="'modal' === props.parentComponentContext"
			:deep-link-ids="[ 'aioseo-post-settings-post-title-row', 'aioseo-post-settings-meta-description-row' ]"
		>
			<core-settings-row
				class="snippet-preview-row"
				no-right-max-width
			>
				<template #name>
					<div>
						<span>{{ strings.serpPreview }}</span>

						<core-tooltip
							:offset="'50px,0'"
							:placement="'bottom'"
						>
							<svg-circle-question-mark/>

							<template #tooltip>
								{{ strings.serpPreviewDocumentation }}
							</template>
						</core-tooltip>
					</div>

					<base-radio-toggle
						:modelValue="postEditorStore.currentPost.generalMobilePrev"
						@update:modelValue="isMobilePreviewEv"
						name="previewGeneralIsMobile"
						class="circle"
						:options="[
							{ label: 'desktop', value: false, activeClass: 'dark', slot: 'desktop' },
							{ label: 'mobile', value: true, slot: 'mobile' }
						]"
					>
						<template #desktop>
							<svg-desktop />
						</template>
						<template #mobile>
							<svg-mobile />
						</template>
					</base-radio-toggle>
				</template>

				<template #content>
					<core-google-search-preview
						:focus-keyphrase="postEditorStore.truseoData?.focusKeyword ?? ''"
						:device="postEditorStore.currentPost.generalMobilePrev ? 'mobile' : 'desktop'"
						:url="tagsStore.liveTags.permalink"
						:title="parseTags(postEditorStore.currentPost.title || postEditorStore.currentPost.tags.title || '#post_title #separator_sa #site_title')"
						:description="parseTags(postEditorStore.currentPost.description || postEditorStore.currentPost.tags.description || '#post_content')"
						:rich-results="seoPreviewStore.richResults"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				id="aioseo-post-settings-post-title-row"
				class="snippet-title-row"
				v-if="allowed('aioseo_page_general_settings')"
				:name="title"
				:key="titleKey"
			>
				<template #content>
					<core-html-tags-editor
						:line-numbers="false"
						single
						@counter="onTitleCount"
						v-model="postEditorStore.currentPost.title"
						:tags-context="`${postEditorStore.currentPost.postType || postEditorStore.currentPost.termType}Title`"
						:defaultMenuOrientation="'modal' === props.parentComponentContext ? 'top' : 'bottom'"
						:default-tags="getDefaultTags('title')"
					>
						<template #tags-description>
							{{ strings.clickToAddTitle }}
						</template>

						<template v-if="
							allowed('aioseo_page_ai_content_settings') &&
							!postEditorStore.currentPost.isWooCommercePageWithoutSchema &&
							postEditorStore.currentPost.postType &&
							!['attachment', 'web-story'].includes(postEditorStore.currentPost.postType)" #append-button
						>
							<ai-generator
								:feature="aiFeatures.metaTitle"
							/>
						</template>
					</core-html-tags-editor>

					<div
						class="max-recommended-count"
						v-html="maxRecommendedPixels(titlePixels, 600)"
					/>
				</template>
			</core-settings-row>

			<core-settings-row
				id="aioseo-post-settings-meta-description-row"
				class="snippet-description-row"
				v-if="allowed('aioseo_page_general_settings')"
				:name="strings.metaDescription"
				:key="descriptionKey"
			>
				<template #content>
					<core-alert
						v-if="showAutogenerateDescriptionsAlert"
						type="yellow"
					>
						<span v-html="strings.autogenerateDescriptionsAlert" />
					</core-alert>

					<core-html-tags-editor
						:line-numbers="false"
						description
						@counter="count => descriptionCount = count.length"
						v-model="postEditorStore.currentPost.description"
						:tags-context="`${postEditorStore.currentPost.postType || postEditorStore.currentPost.termType}Description`"
						:defaultMenuOrientation="'modal' === props.parentComponentContext ? 'top' : 'bottom'"
						:default-tags="getDefaultTags('description')"
					>
						<template #tags-description>
							{{ strings.clickToAddDescription }}
						</template>

						<template v-if="
							allowed('aioseo_page_ai_content_settings') &&
							!postEditorStore.currentPost.isWooCommercePageWithoutSchema &&
							postEditorStore.currentPost.postType &&
							!['attachment', 'web-story'].includes(postEditorStore.currentPost.postType)" #append-button
						>
							<ai-generator
								:feature="aiFeatures.metaDescription"
							/>
						</template>
					</core-html-tags-editor>

					<div
						class="max-recommended-count"
						v-html="maxRecommendedCount(descriptionCount, 160)"
					/>
				</template>
			</core-settings-row>
		</core-card>

		<metabox-social
			v-if="'modal' !== props.parentComponentContext && allowed('aioseo_page_social_settings')"
			:parent-component-context="props.parentComponentContext"
		/>
	</div>
</template>

<script setup>
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue'

import {
	useOptionsStore,
	usePostEditorStore,
	useRootStore,
	useSeoPreviewStore,
	useTagsStore
} from '@/vue/stores'

import { __, sprintf } from '@/vue/plugins/translations'
import { allowed } from '@/vue/utils/AIOSEO_VERSION'
import { measureTextWidth } from '@/vue/utils/measureTextWidth'
import { useMaxCounts } from '@/vue/composables/MaxCounts'
import { useTags } from '@/vue/composables/Tags'
import { useTruSeoScore } from '@/vue/composables/TruSeoScore'
import { debounce } from '@/vue/utils/debounce'
import { aiFeatures } from '../partials/ai-content/utils'

import links from '@/vue/utils/links'

import AiGenerator from '../partials/general/ai/Generator'
import BaseRadioToggle from '@/vue/components/common/base/RadioToggle'
import CoreAlert from '@/vue/components/common/core/alert/Index'
import CoreCard from '@/vue/components/common/core/Card'
import CoreGoogleSearchPreview from '@/vue/components/common/core/GoogleSearchPreview'
import CoreHtmlTagsEditor from '@/vue/components/common/core/HtmlTagsEditor'
import CoreSettingsRow from '@/vue/components/common/core/SettingsRow'
import CoreTooltip from '@/vue/components/common/core/Tooltip'
import MetaboxSocial from './Social'
import SvgCircleQuestionMark from '@/vue/components/common/svg/circle/QuestionMark'
import SvgDesktop from '@/vue/components/common/svg/Desktop'
import SvgMobile from '@/vue/components/common/svg/Mobile'

const td = import.meta.env.VITE_TEXTDOMAIN

const props = defineProps({
	disabled : {
		type : Boolean,
		default () {
			return false
		}
	},
	parentComponentContext : String
})

const optionsStore    = useOptionsStore()
const postEditorStore  = usePostEditorStore()
const rootStore        = useRootStore()
const seoPreviewStore  = useSeoPreviewStore()
const tagsStore        = useTagsStore()

const titlePixels       = ref(0)

// The SEO title uses a pixel counter — search engines truncate titles by pixel
// width, so this tracks how the TruSEO title-width check measures.
const onTitleCount = (count) => {
	titlePixels.value = measureTextWidth(count.text || '')
}
const descriptionCount  = ref(0)
const titleKey          = ref('title' + 0)
const descriptionKey    = ref('description' + 0)

const { parseTags } = useTags({ separator: undefined })
const { maxRecommendedCount, maxRecommendedPixels } = useMaxCounts()
const { runAnalysis } = useTruSeoScore()

const strings = {
	searchAppearance              : __('Search Appearance', td),
	socialAppearance              : __('Social Appearance', td),
	serpPreview                   : __('SERP Preview', td),
	serpPreviewDocumentation      : __('SERP: Search Engine Results Page preview. Your site\'s potential appearance in Google search results. Final display may vary, but this preview closely resembles it.', td),
	clickToAddTitle               : __('Click on the tags below to insert variables into your title.', td),
	metaDescription               : __('Meta Description', td),
	clickToAddDescription         : __('Click on the tags below to insert variables into your meta description.', td),
	autogenerateDescriptionsAlert : sprintf(
		// Translators: 1 - The plugin short name ("AIOSEO"), 2 - A link to "Search Appearance > Advanced".
		__('Warning: You have disabled Autogenerate Descriptions and are using the default description format. %1$s will not output a description unless you enter a custom one. You can enable Autogenerate Descriptions under %2$s.', td),
		import.meta.env.VITE_SHORT_NAME,
		links.getPlainLink(
			__('Search Appearance > Advanced', td),
			rootStore.aioseo.urls.aio.searchAppearance + '#/advanced'
		)
	)
}

const title = computed(() => {
	return sprintf(
		// Translators: 1 - The type of page (Post, Page, Category, Tag, etc.).
		__('%1$s Title', td),
		postEditorStore.currentPost.type
	)
})

const showAutogenerateDescriptionsAlert = computed(() => {
	if (!optionsStore.internalOptions.internal.deprecatedOptions.includes('autogenerateDescriptions')) {
		return false
	}

	const defaultDescription = 'post' === postEditorStore.currentPost.context
		? optionsStore.dynamicOptions.searchAppearance.postTypes[postEditorStore.currentPost.postType].metaDescription
		: optionsStore.dynamicOptions.searchAppearance.taxonomies[postEditorStore.currentPost.termType].metaDescription

	return defaultDescription === postEditorStore.currentPost.description && !optionsStore.options.deprecated.searchAppearance.advanced.autogenerateDescriptions
})

const isMobilePreviewEv = (ev) => {
	postEditorStore.changeGeneralPreview(ev)
}

const getDescriptionTags = () => {
	if ('post' !== postEditorStore.currentPost.context) {
		return [ 'taxonomy_title', 'separator_sa', 'taxonomy_description' ]
	}

	if ('attachment' === postEditorStore.currentPost.postType) {
		return [ 'attachment_caption', 'separator_sa', 'site_title' ]
	}

	if ('product' === postEditorStore.currentPost.postType) {
		return [ 'post_excerpt', 'post_content' ]
	}

	return [ 'post_excerpt', 'post_content', 'separator_sa' ]
}

const getDefaultTags = (location) => {
	switch (location) {
		case 'title':
			return 'post' === postEditorStore.currentPost.context
				? [
					'post_title',
					'separator_sa',
					'site_title'
				]
				: [
					'taxonomy_title',
					'separator_sa',
					'site_title'
				]
		case 'description':
			return getDescriptionTags()
	}
}

watch(() => postEditorStore.currentPost.title, () => {
	debounce(() => { runAnalysis({ postId: postEditorStore.currentPost.id }) }, 750)
})

watch(() => postEditorStore.currentPost.description, () => {
	debounce(() => runAnalysis({ postId: postEditorStore.currentPost.id }), 750)
})

onMounted(() => {
	window.aioseoBus.$on('updateTitleKey', () => {
		titleKey.value = 'title' + Math.random(0, 999)
	})

	window.aioseoBus.$on('updateDescriptionKey', () => {
		descriptionKey.value = 'description' + Math.random(0, 999)
	})
})

onBeforeUnmount(() => {
	window.aioseoBus.$off('updateTitleKey')
	window.aioseoBus.$off('updateDescriptionKey')
})
</script>
<style lang="scss">
// The Social Appearance section reuses the standalone Social component, whose root
// .aioseo-tab-content would otherwise inherit nested-tab padding and inset the card
// relative to Search Appearance. Zero it so both cards align. Scoped to the app so it
// outranks Main.vue's nested-tab padding no matter which CSS chunk loads last (they tie
// on specificity otherwise, which misaligns the cards in the Divi page-builder bundle).
.aioseo-app.aioseo-post-settings .aioseo-tab-content.aioseo-post-general > .aioseo-tab-content.aioseo-post-social {
	padding: 0;
}

// Modal-specific styles (opened from metabox)
.aioseo-modal-content {
	.aioseo-settings-row {
		--aioseo-gutter: 10px;
		row-gap: 12px;

		.settings-name .name {
			margin: 0;
		}
	}

	> .aioseo-settings-row {
		border: none;
		margin-bottom: 0!important;
	}

	.snippet-title-row,
	.snippet-description-row {
		position: relative;
		display: block;

		.settings-name {
			margin-bottom: 8px;
		}

		.aioseo-description {
			display: none;
		}

		.add-tags {
			.aioseo-add-template-tag {
				@media screen and (max-width: 520px) {
					display: none;
				}
			}
		}
	}

	.snippet-title-row {
		margin-top: 12px;
	}

	.snippet-pillar-row {
		display: none;
	}

}
</style>